---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook-fbs
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    webhook_url: AgBfQ8o7UqFRSBXLtM74LYYt+HlhAQfZw6EmHFiVblV8GEbKMFl5nghi+45jz5QsK1mHCVm00Tqyug+QfhcUqUuT2QgEa96bGB+yRPoUfijXMWyZt+7Q+iW3JohMa3xIchewROgt3gknFymNxc4go0F/0QmPlxNieke5CEMzXpL1rPSY9szOQTbicQNbgoYpXLflny4ljY15+vWgcYylqg9lgXYzyBVCRE9IV+lD3N2vyez0cY7hRKCLDuVbP6ubbYkClnSLbhZwVe0XUan0hmpVYznROjyLSQny1t3m6/34OBKsvgHCY61seIW5nw2ZccwSfS2dclPr3okQMuBQAmEwhHVP9IJWKI31r1rjw/YKywXPEaZ+aifPXF+oBcuU35h5EvoBspC5LDtt8dmQF6u7P4wVKzDnLaG43rNMvCkm6TCmjYTZfYJxLN1ggvpxSFZ9xu+N8ZuRS6brJgbv8BQPbSIAV4z3eYuW+1iKgB3cVnbwDgqFI6CFBG40P0zGMW/dcVE77t2lmXP6RqS84eu6ZPRDL9ozsROEd0bNwEpkCaQ0XHeouF85YqPKTH+6vKO3GRdlQNzGTnH2OqLM/j7bo6rjFUsBlWEUWseFVUeONLZET5VxfcNdRV0DV9ngyZqcVH5sOnXMZHxzrrxsGM2QySuRDX9pFlOYbZeAsLK8O4TL4lJJGRmu1y8qghzKxJs6R+jrrBsoggelJgmCxtFK72svZEZbJwzT5Ia5NER2dlH8YlBR5fEtXu9byWicBQUxpnEvW71aTR7ViQv1D51nbN1nSajfPDCFN/0nil58QcP7uSDu5UGhX/j3y5yQsHJ21mlCcLPPFDTxOoqwX8dGbF00NGKS0i0P
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook-fbs
      namespace: kube-prometheus-stack
