apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-webhook-proxy-templates
data:
  webhook_proxy.conf.template: |
    server {
      location / {
        proxy_pass ${DISCORD_WEBHOOK_URL};
      }

      location /health {
        return 200;
      }
    }
