---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook-play-when
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    webhook_url: AgCVbQfYU7iGXMRgyr7zG9JoussnYSsL1CZ3WQALsS1EZqaAiBZYxTHXzYVLVbjRZZXsCgKnEP11pkiLndEzBObSFS/B7yMcyg0ku9alWzECKjOy3EqQ7/7/hdEBQPROvQvdRpjRTUEwaHIqTc2H4GJnlZFMRw8Veeh1qlxp1qba9oLRTxlKdYXOZu0QX/ZwEuN0LNZ6mrvmSPNxAi9UvXThnFwiZ/lIUdJsiz+iMPM73YsiHB6y2jb+09J/tzF16LmEjVgE3C9h0s7ljwErWMCLy5siR4Kf5/sANIH/0M18sZfl1Hd0c1xQxCUdCEa5lzpkM9a8oHS0qF0VTmhNGMBlHz0tfgKhrmFiDh8AO7NsQ3lRdSKAVFHWw3sSkpp97NddWEEwlGqZ5IGuaBUD9svunm4Ef9rIvUGOcYnXpAX8MCulebKe7/s1zFdXj3lUETv6CXEVpTwRDHQcv0zTYEKYlrQGLOj/KnuY3nw2KyZ420AuWRGpgD0yi7cSFvdDz0t3aDsRfnuFifRDtCzhFlS8aG4hrl8WAwRLkg7+cVyVQoV3jaGr0gwGFdOEZyqu04JvcqhbdhMRea/I7FbRWtNAcWQFf7c7zkuf1dtyTcuAkUBNwvhTQMVM42rrmlyOcxPxcpAORzQFzLCRL5qmOeiG/8VIo/zInz5NH4k7TFhSmB1Mc/91bAErmdQZkBlYdfCzzWziFF225husGJgmKrj9zLY9kmdLgnUpP9etcBCztXr85hf1ikH3D8QwgFqqcCsrqI2OIxJzvVcRNQkV+OtzCaIvk62Ft0rOr+sqQ6FNYaY+rNgUJ8u17oQdlb26SlCQbRTf/jMi3BRviRmKVRCvgdAegGUGcu1d
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook-play-when
      namespace: kube-prometheus-stack
