apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/seaweed.yaml
images:
  - name: seaweedfs
    newName: chrislusf/seaweedfs
    newTag: "4.13"
configurations:
  - configurations/images.yaml
buildMetadata: [managedByLabel]
