apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/seaweed.yaml
  - resources/sealed-secret-seaweed-s3-config.yaml
images:
  - name: seaweedfs
    newName: chrislusf/seaweedfs
    newTag: "4.09"
configurations:
  - configurations/images.yaml
buildMetadata: [managedByLabel]
