apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/storage-class-longhorn-local-ext4.yaml
  - resources/storage-class-longhorn-local-xfs.yaml
buildMetadata: [managedByLabel]
