---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seaweed-s3-config
  namespace: seaweed
spec:
  encryptedData:
    s3-config.json: AgAIiiT2QYW7MttQsTGgTi/zCC9JXUwxpqG7nH5tiokAADy2Xn1zNmwunT2vPV5MfkV5Pg0l6ATTYJnVctA4NIYBjHQgWRhNfaiFXDOS8Y/KEamEzGhrbFwf4CAZ15JAcuADp9hXNI/ZDV6jmejjuzm/NX6ZQrTCjIJ/+H6Ms6EGjV3YAJJefq+r2fflUARLa1zNAL7ku1CBoFP7UBmF9St18AFhbOigDJ5whkm7vbwcIFMRPB1pMQ4NDYfnoy0HCkZjUWQmaceuM8PvFS5LZWd8RqdaB17/L3SuFFYNpdmG0pOzJEqRe1u/jSuqNKXnUYznEjS6Vq8wBuVxmGAQdnrxm+Mazxu6D9fH4Iz7Z5kopucNN2IOlSuEyDDIX76lRsEoWKIf2mP8PXValjBp58/qAn18yRGEEKk0L2HExJveeckTZRe18xIJ8tfpLFA8P9U41sI5zfU99BHR4hUqr/tBdV/Z8TrXI0/2HTMg9qPC57ZyGCkt11JaurBJkZbxcETpWorsJ1Of31jodEyfdstyaOQoAhM2e5LcXxwX2R+H1u7R27HUy643XtyXtBYSXstATtwuv5Zf41OShC5SH51sdlF57aGZbTPnm5prpVJgsDLwEjQjulyteG4vV+5DBkk1M/4xuddb0NhibIZrPWHs0jguCP3jZzlSyk4k9EFkA1DS5oPwd0eGJnu9Wugy8lM=
  template:
    metadata:
      creationTimestamp: null
      name: seaweed-s3-config
      namespace: seaweed
