---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seaweed-s3-config
  namespace: seaweed
spec:
  encryptedData:
    s3-config.json: AgBZdcJ6DiPRhFCZr6Q9+nnYckEQvZIeP0MpoVdx9h2uEkXXMWaGeC6EM55d/c1lvM+VnRnHytsRHccptNtEbkI0uGpyGIdVzl62OZH8Bq/tKvfw+I3NrGOjJTDW7uNSvW0WZSH1pedjTSzfUx+sui1UQggW8y73fgbL1PmxVc9xQjKbDrc7ztEJptqqO7qtLdr9n+oE2+adhOugdEXqXy4yIg2tVdEWBAT1n1UxfO/+c3BlqWu5dKjaGJMzV48CJWoDbQ38F2GG93D1ZDyNpDgqIItICDMqhoUQWb6uFL6Cl/R1q0phVpxghkVLLBJRIMkhAZZWZ9OQK3cu/oCggzCmQYMLx8TCbyS9gg8q9c4dwvv6/4X81bLvigTck4hxcVzYq2vMwL1zzy8ZY3OImq9+J7Y23Auaffg/53ckHIqBcc9jxzT54L/eO1n12uo9xc8dyJIe8eRHfIbs4+A7587LZbsJwH9AWiKsRsE7u7VmLq81CzMNi6OtD7kX9SUWHQQJJn2PD5HQCMdLRYWA1EDwdGlY17fWpoK/W7efL+Jo2//qNISIq8jfPEnB9bBNvKXkVABVMtgDR0yCGab9ZMSfQAKxnO/9yP6uLLSuuIuEzWGY/cvu01dAfyUDu+4kgErnXArmdVPTjhB+KrE2038CWufSFrlTid1p7wPH/NFAffd6yamv1SuD+LHVBjoL0Bk=
  template:
    metadata:
      creationTimestamp: null
      name: seaweed-s3-config
      namespace: seaweed
