---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seaweed-s3-config
  namespace: seaweed
spec:
  encryptedData:
    s3-config.json: AgADbyllxEuYqF/GXhEV7Ibx8RWgAeUnnfY41S8luywHpgfStDuBwZNJ/5BF3qayPfqI3TUl53Ev27sV89od8Gy2GkXg15fDMXzQlowoA1c9EnmSDiYKVS/nWTtuSrAUUX48+Wfo9eQHrcE1IUo4RpoeI7GC+jtZNLKX2ObtCSRVN5QwDqkHszywxKCOfpaYWdY1evJX99Vz1oY580xL7k4AZSvGeWmp6ybd49wkYVNgayEfo0tkFljukTzpg0yPOV8ozc8DgViYg2C3tbVFVG+dl/Y8TWzaiX2rGEAiJHVcROnxherjG54ydpeuXWv/xUyHrUO7iSSBGfuIZDmbAMe5Bs69JODaHW4Jc6Cmz4wgty+kHgbRuFUrEWCc3vpPHb8XXE/JTg0ejDB8vqEygkuSLPfC+7zc1gezVKZvj92juCz3S+mkXjVG7PIAbiV+efRCfljmSonNUgkC1z2VosRaOhQ9UexJmq8tz8dGixna44S0lAC7WLRYzwsJyIVhp4fcLIefgFACFZe2hUxBRt9dl8XcA/fqHQuFG+5Ivc1Kdt2RrHEH2SGOcLdCJzGMyXng0SQ1bBfmOOub/C2efA3RuG1jiYlxQG8saQZCiawqs82g62LpnXi/731m5ue37CbK193ziWG/8DkJ50a5fMVduc9xJIJriQX+JEgmCeKIT2WTcVxKS+RTcchthkqiOphQSU9NLWBePQEywzdCd/iV7iU913rsnB/ZbV4o5kJRueF/wnS8iyc0kBI0QSz8nHrIAuujVkQSW/tO8Xfbs9QxjYI7zvwJNWwmDZgJP3H0A6taHrf9b8SYu0uq351Nwz4zTD0lhfno97YkiSorDh84c3hiBQagZESdgqQuk9jRDRqOVmcoztanlNIoE4W0EA2+dZKM9tTNH8qLYhuNWHYYA6NTJiAZt5PyH9ZZHXCG9W6eGYwY4mV0rh2VBL1DNYZsZPR6u75kIbhoD30wrGyUHs14i8O/ZYlKhxocQzoNUlFdwR+CadoqFeeuDev5lm6yz6JFnKxkTNN0S9HZ88NLfUvBRKqmwCVNTIlM6x4bAhsSOGBWTzaVW/YzE24V9zZSemGvSST0SmQnK8SUWnau9X9UFnL5R5PW1uRGykr4bSJUSiE73QT/l0o+XoLM3efUW9RwhtzlNmUvRk6kUoVCb6yLREUUA7PBaQUW+A4ipXqJC3LJRfFCilzpxvgHbk1yZOuynEumcLM1fyGbl3Bley0fKIak8EPs3VikZJhYjzvkc+soUJgVI+IyuMXIzGYovkaTP96KBznbD3tLgZ+8B5Ox1pv9DLuk1cp/MdikG1Y0W4zAiRr0xBF28xWk9s030T8NZmLAu5X4RzdsHoSkIVT7AdZUHTNHBtjhG+o5qcis4fH5lG8CU66DpklU0EspU7/07xX7wiNE3byq7846EgZDTjBAO8aVbKpehcd7RYCNPq9Fae2tUkJEiJqrMO30NPAuE3gMv8LDIhDAHRAd8m+BBFWh3piwBA==
  template:
    metadata:
      creationTimestamp: null
      name: seaweed-s3-config
      namespace: seaweed
