namespace: system-upgrade

resources:
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.19.0/crd.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.19.0/system-upgrade-controller.yaml
  - server-plan.yaml
  - agent-plan.yaml
