apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/deployment.yaml
  - ./resources/ingress.yaml
  - ./resources/network-policy.yaml
  - ./resources/pvc-database.yaml
  - ./resources/pvc-uploads.yaml
  - ./resources/sealed-secret.yaml
  - ./resources/service.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/instance: tududi
      app.kubernetes.io/name: tududi
images:
  - name: tududi
    newName: chrisvel/tududi
    newTag: "0.87"
replacements:
# avoid repeating the host name in the ingress tls config
- source:
    kind: Ingress
    fieldPath: spec.rules.0.host
  targets:
    - select:
        kind: Ingress
        name: tududi
      fieldPaths:
        - spec.tls.0.hosts.0
      options:
        create: true
buildMetadata: [managedByLabel]
