apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/mailgun-keepalive-cronjob.yaml
  - resources/mailgun-keepalive-recipient-address.yaml
  - resources/mailgun-keepalive-sending-api-key.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/instance: mailgun-keepalive
      app.kubernetes.io/name: mailgun-keepalive
images:
  - name: curl
    newName: curlimages/curl
    newTag: 8.18.0
buildMetadata: [managedByLabel]
